build:
  environment:
    php: 7.2

project_setup:
  before:
    - sudo service start mysql || true
    - mysql -e "CREATE DATABASE owuan_mysql_test";

filter:
  excluded_paths:
    - "tests/*"
  dependency_paths:
    - "vendor/*"